version: '3'

services:

  ##  MYSQL und PHP
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - data-mysql-5.7:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test_db
      MYSQL_USER: sh
      MYSQL_PASSWORD: 12345
    networks:
       test_net:
          ipv4_address: 172.29.1.1

  ##  PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_USER: sh
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      test_net:
        ipv4_address: 172.29.1.4

  ##  PHP
  web:
    build: ./php/
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./pub/:/var/www/html/
    stdin_open: true
    tty: true
    networks:
      test_net:
        ipv4_address: 172.29.1.2

  ##  Apache
  apache:
    build: ./apache/
    container_name: apache_web
    hostname: www.shahriar-docker.test
    depends_on:
      - db
      - web
    volumes:
      - ./docker/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./pub/:/var/www/html/
      - ./logs:/var/log/apache2
      - /var/run/docker.sock:/tmp/docker.sock:ro

    stdin_open: true
    tty: true
    environment:
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__REMOTE_PORT: 10000;
      PHP_IDE_CONFIG: "serverName=www.shahriar-docker.test"
      XDEBUG_CONFIG: "remote_port=10000 remote_autostart=1"
    logging:
      driver: json-file
      options:
        max-size: "4k"
        max-file: "5"
    networks:
      test_net:
        ipv4_address: 172.29.1.3

  ##MEMCACHED
  memcached:
    image: memcached:latest
    hostname: memcached
    container_name: Project1_memcached
    volumes:
      - ./logs/memcached/:/var/log/memcache
    entrypoint:
      - memcached
      - -m 64

    depends_on:
      - db

    networks:
      test_net:
        ipv4_address: 172.29.1.6

##
networks:
  test_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

##
volumes:
  data-mysql-5.7:
    driver: local
